### ISSUE TITLE
Ability To Fetch Old Articles

### ISSUE THREAD

**Issue by pidus** [ahmaabdo/ReadifyRSS#3]
I was using Inoreader before Readify. It has the ability to fetch old articles, which Readify lacks. Please add this feature.

**Comment by pidus** [comment]
Inoreader: 
![screenshot_2018-03-06-11-12-25-079_com innologica inoreader](https://user-images.githubusercontent.com/11857051/37015946-ecf8c178-212f-11e8-954f-1396a9578dee.png)

**Comment by pidus** [comment]
Readify: 
![screenshot_2018-03-06-11-12-29-407_ahmaabdo readify rss](https://user-images.githubusercontent.com/11857051/37015966-fef0d488-212f-11e8-8f5e-b74c3814417b.png)

**Comment by ahmaabdo** [comment]
"Time that the entries will be kept" from Settings activity will fetch old articles.
